### ISSUE TITLE
Nuxt 3 "intlify.vuei18n.options.mjs" does not provide an export named 'default'

### ISSUE THREAD

**Issue by sikeat7** [intlify/nuxt3#64] opened 2022-05-03 09:18 UTC
Hi! I'm my previous project and my fresh project got an error after I'm re-install node_modules. Is it a bug because my previous version used to work fine but after I deleted **node_modules** and re-install it back this error occurred. And fresh project also got this error. This is bug from Nuxt3 ? Thank you.

<img width="1440" alt="Screen Shot 2022-05-03 at 3 38 41 PM" src="https://user-images.githubusercontent.com/12691222/166429777-7f34adf4-da0a-450a-99cd-9eb0d7ca03f0.png">

**Comment by PiotrekPKP** [comment] 2022-05-03 09:19
I think be both opened similar issues at the same time haha :D
Yeah, I've just got the same problem. Let's hope it'll be fixed soon

**Comment by sikeat7** [comment] 2022-05-03 09:23
> I think be both opened similar issues at the same time haha :D Yeah, I've just got the same problem. Let's hope it'll be fixed soon

Yes, I think it occurred while Nuxt3 updated some core. Hope Intlify's Team fix it soon.

**Comment by ozancakir** [comment] 2022-05-03 13:44
Its working when nuxt version downgraded to rc1 release, hope this will be fixed for rc2 and future releases.

**Comment by FlyingWraptor** [comment] 2022-05-03 13:45
I've tried the rc1 release but to no avail. What does your package.json look like?

**Comment by FlyingWraptor** [comment] 2022-05-03 14:05
After forcing the versions in package.json I can confirm this has solved the issue
```json

  "overrides": {
    "nuxi": "3.0.0-rc.1",
    "nuxt": "3.0.0-rc.1",
    "@nuxt/kit": "3.0.0-rc.1",
    "@nuxt/schema": "3.0.0-rc.1",
    "@nuxt/vite-builder": "3.0.0-rc.1"
  }
```

**Comment by FlyingWraptor** [comment] 2022-05-06 12:37
@yacosta738 
> Any update about this issue? I can't work with the rc.2 version

There have been no update since this issue started. I've tested RC.2 myself today and the problem still persist. I would recommend using the patch above, for now.

**Comment by yacosta738** [comment] 2022-05-06 12:38
@FlyingWraptor thank you.

**Comment by Shizopo** [comment] 2022-05-12 11:15
Same issue on freshly created project with `"nuxt": "3.0.0-rc.3"`.

**Closed** 2022-05-12 16:58 UTC

**Comment by exreplay** [comment] 2022-05-16 09:04
I found that the virtual template for `intlify.vuei18n.options.mjs` is not progressed by the unplugin loader https://github.com/intlify/nuxt3/blob/main/packages/nuxt3/src/loader.ts

But if you add `write: true` to `addTemplate` it does get found by the loader and modified by the `transform`.

For anyone who can use yarn patches i created one which adds the `write: true`.

package.json
```json
{
  "resolutions": {
    "@intlify/nuxt3": "patch:@intlify/nuxt3@npm:0.2.1#.yarn/patches/@intlify-nuxt3-npm-0.2.1-56d98f6125.patch"
  }
}
```

.yarn/patches/@intlify-nuxt3-npm-0.2.1-56d98f6125.patch
```
diff --git a/dist/module.mjs b/dist/module.mjs
index cb993e5714666b1b93aa6262d85686d95cee2a16..f17706e9d407224e38f51bd2c3b02b94f475c0af 100644
--- a/dist/module.mjs
+++ b/dist/module.mjs
@@ -106,6 +106,7 @@ const IntlifyModule = defineNuxtModule({
     const localeResources = await resolveLocales(localePath) || [];
     addTemplate({
       filename: INTLIFY_VUEI18N_OPTIONS_VIRTUAL_FILENAME,
+      write: true,
       getContents: () => {
         return `${nuxt.options.dev ? "// 'vueI18n' option loading ..." : ""}`;
       }

```

One thing i was wondering is, why is there an extra loader which modfies the code when you could just add the logic to the `getContents` function. I tested it locally and it was working. https://github.com/intlify/nuxt3/blob/d8afcd516268bd5e2d2bd1b5974fe53e7dc496ae/packages/nuxt3/src/module.ts#L74

**Comment by apss-pohl** [comment] 2022-05-17 06:45
> I found that the virtual template for `intlify.vuei18n.options.mjs` is not progressed by the unplugin loader https://github.com/intlify/nuxt3/blob/main/packages/nuxt3/src/loader.ts
> 
> But if you add `write: true` to `addTemplate` it does get found by the loader and modified by the `transform`.
> 
> For anyone who can use yarn patches i created one which adds the `write: true`.
> 
> package.json
> 
> ```json
> {
>   "resolutions": {
>     "@intlify/nuxt3": "patch:@intlify/nuxt3@npm:0.2.1#.yarn/patches/@intlify-nuxt3-npm-0.2.1-56d98f6125.patch"
>   }
> }
> ```
> 
> .yarn/patches/@intlify-nuxt3-npm-0.2.1-56d98f6125.patch
> 
> ```
> diff --git a/dist/module.mjs b/dist/module.mjs
> index cb993e5714666b1b93aa6262d85686d95cee2a16..f17706e9d407224e38f51bd2c3b02b94f475c0af 100644
> --- a/dist/module.mjs
> +++ b/dist/module.mjs
> @@ -106,6 +106,7 @@ const IntlifyModule = defineNuxtModule({
>      const localeResources = await resolveLocales(localePath) || [];
>      addTemplate({
>        filename: INTLIFY_VUEI18N_OPTIONS_VIRTUAL_FILENAME,
> +      write: true,
>        getContents: () => {
>          return `${nuxt.options.dev ? "// 'vueI18n' option loading ..." : ""}`;
>        }
> ```
> 
> One thing i was wondering is, why is there an extra loader which modfies the code when you could just add the logic to the `getContents` function. I tested it locally and it was working.
> 
> https://github.com/intlify/nuxt3/blob/d8afcd516268bd5e2d2bd1b5974fe53e7dc496ae/packages/nuxt3/src/module.ts#L74

Great work, I can confirm, this also works for me with Nuxt CLI v3.0.0-rc.3-27545866.cd37a21 - thank you! 
Do you plan to do a pull request here: https://github.com/intlify/nuxt3?

**Comment by exreplay** [comment] 2022-05-17 07:41
@apss-pohl There has already been created a PR by @FlyingWraptor. Thank you for that!
